# PySNMP SMI module. Autogenerated from smidump -f python AUTOTALKS-EN302-MIB
# by libsmi2pysnmp-0.1.3 at Sun Sep 29 09:49:23 2013,
# Python version sys.version_info(major=2, minor=7, micro=3, releaselevel='final', serial=0)

# Imports

( Integer, ObjectIdentifier, OctetString, ) = mibBuilder.importSymbols("ASN1", "Integer", "ObjectIdentifier", "OctetString")
( NamedValues, ) = mibBuilder.importSymbols("ASN1-ENUMERATION", "NamedValues")
( ConstraintsIntersection, ConstraintsUnion, SingleValueConstraint, ValueRangeConstraint, ValueSizeConstraint, ) = mibBuilder.importSymbols("ASN1-REFINEMENT", "ConstraintsIntersection", "ConstraintsUnion", "SingleValueConstraint", "ValueRangeConstraint", "ValueSizeConstraint")
( atlkMgmt, ) = mibBuilder.importSymbols("AUTOTALKS-REG", "atlkMgmt")
( InterfaceIndex, ) = mibBuilder.importSymbols("IF-MIB", "InterfaceIndex")
( ModuleCompliance, ObjectGroup, ) = mibBuilder.importSymbols("SNMPv2-CONF", "ModuleCompliance", "ObjectGroup")
( Bits, Integer32, ModuleIdentity, MibIdentifier, MibScalar, MibTable, MibTableRow, MibTableColumn, TimeTicks, Unsigned32, ) = mibBuilder.importSymbols("SNMPv2-SMI", "Bits", "Integer32", "ModuleIdentity", "MibIdentifier", "MibScalar", "MibTable", "MibTableRow", "MibTableColumn", "TimeTicks", "Unsigned32")
( TruthValue, ) = mibBuilder.importSymbols("SNMPv2-TC", "TruthValue")

# Objects

en302Mib = ModuleIdentity((1, 3, 6, 1, 4, 1, 38405, 1, 3)).setRevisions(("2012-12-19 00:00",))
if mibBuilder.loadTexts: en302Mib.setOrganization("Autotalks")
if mibBuilder.loadTexts: en302Mib.setContactInfo("Grand Netter Building\nPOB 3846, Kfar-Netter 40593, Israel\nPhone: (+972)-9-886-5300\nFax:   (+972)-9-886-5301\ninfo@auto-talks.com")
if mibBuilder.loadTexts: en302Mib.setDescription("Autotalks Ltd. SMIv2 MIB for functionality defined by ETSI\nEN 302 and includes extensions not required by the standard.")
en302Conformance = MibIdentifier((1, 3, 6, 1, 4, 1, 38405, 1, 3, 1))
en302Groups = MibIdentifier((1, 3, 6, 1, 4, 1, 38405, 1, 3, 1, 1))
en302Compliances = MibIdentifier((1, 3, 6, 1, 4, 1, 38405, 1, 3, 1, 2))
en302Fac = MibIdentifier((1, 3, 6, 1, 4, 1, 38405, 1, 3, 2))
en302Cam = MibIdentifier((1, 3, 6, 1, 4, 1, 38405, 1, 3, 2, 1))
en302CamTxPeriod = MibScalar((1, 3, 6, 1, 4, 1, 38405, 1, 3, 2, 1, 1), Unsigned32().subtype(subtypeSpec=ValueRangeConstraint(10, 1000))).setMaxAccess("readwrite").setUnits("milliseconds")
if mibBuilder.loadTexts: en302CamTxPeriod.setDescription("Time period between sequential CAMs.")
en302CamTxIf = MibScalar((1, 3, 6, 1, 4, 1, 38405, 1, 3, 2, 1, 2), InterfaceIndex()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: en302CamTxIf.setDescription("MAC interface used for CAM transmission.")
en302CamTxEnabled = MibScalar((1, 3, 6, 1, 4, 1, 38405, 1, 3, 2, 1, 3), TruthValue()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: en302CamTxEnabled.setDescription("Whether CAM transmission is enabled.")

# Augmentions

# Groups

en302MibGroup = ObjectGroup((1, 3, 6, 1, 4, 1, 38405, 1, 3, 1, 1, 1)).setObjects(*(("AUTOTALKS-EN302-MIB", "en302CamTxPeriod"), ("AUTOTALKS-EN302-MIB", "en302CamTxIf"), ("AUTOTALKS-EN302-MIB", "en302CamTxEnabled"), ) )
if mibBuilder.loadTexts: en302MibGroup.setDescription("All objects in AUTOTALKS-EN302-MIB")

# Compliances

en302Compliance = ModuleCompliance((1, 3, 6, 1, 4, 1, 38405, 1, 3, 1, 2, 1)).setObjects(*(("AUTOTALKS-EN302-MIB", "en302MibGroup"), ) )
if mibBuilder.loadTexts: en302Compliance.setDescription("Compliance statement covering entire AUTOTALKS-EN302-MIB")

# Exports

# Module identity
mibBuilder.exportSymbols("AUTOTALKS-EN302-MIB", PYSNMP_MODULE_ID=en302Mib)

# Objects
mibBuilder.exportSymbols("AUTOTALKS-EN302-MIB", en302Mib=en302Mib, en302Conformance=en302Conformance, en302Groups=en302Groups, en302Compliances=en302Compliances, en302Fac=en302Fac, en302Cam=en302Cam, en302CamTxPeriod=en302CamTxPeriod, en302CamTxIf=en302CamTxIf, en302CamTxEnabled=en302CamTxEnabled)

# Groups
mibBuilder.exportSymbols("AUTOTALKS-EN302-MIB", en302MibGroup=en302MibGroup)

# Compliances
mibBuilder.exportSymbols("AUTOTALKS-EN302-MIB", en302Compliance=en302Compliance)
