# PySNMP SMI module. Autogenerated from smidump -f python AUTOTALKS-REG
# by libsmi2pysnmp-0.1.3 at Tue Aug  4 15:19:14 2015,
# Python version sys.version_info(major=2, minor=7, micro=6, releaselevel='final', serial=0)

# Imports

( Integer, ObjectIdentifier, OctetString, ) = mibBuilder.importSymbols("ASN1", "Integer", "ObjectIdentifier", "OctetString")
( NamedValues, ) = mibBuilder.importSymbols("ASN1-ENUMERATION", "NamedValues")
( ConstraintsIntersection, ConstraintsUnion, SingleValueConstraint, ValueRangeConstraint, ValueSizeConstraint, ) = mibBuilder.importSymbols("ASN1-REFINEMENT", "ConstraintsIntersection", "ConstraintsUnion", "SingleValueConstraint", "ValueRangeConstraint", "ValueSizeConstraint")
( Bits, Integer32, ModuleIdentity, MibIdentifier, TimeTicks, enterprises, ) = mibBuilder.importSymbols("SNMPv2-SMI", "Bits", "Integer32", "ModuleIdentity", "MibIdentifier", "TimeTicks", "enterprises")

# Objects

autotalks = ModuleIdentity((1, 3, 6, 1, 4, 1, 38405)).setRevisions(("2014-06-18 00:00","2012-09-03 00:00",))
if mibBuilder.loadTexts: autotalks.setOrganization("Autotalks")
if mibBuilder.loadTexts: autotalks.setContactInfo("Grand Netter Building\nPOB 3846, Kfar-Netter 40593, Israel\nPhone: (+972)-9-886-5300\nFax:   (+972)-9-886-5301\ninfo@auto-talks.com")
if mibBuilder.loadTexts: autotalks.setDescription("Autotalks top-level OID registration module")
atlkMgmt = MibIdentifier((1, 3, 6, 1, 4, 1, 38405, 1))

# Augmentions

# Exports

# Module identity
mibBuilder.exportSymbols("AUTOTALKS-REG", PYSNMP_MODULE_ID=autotalks)

# Objects
mibBuilder.exportSymbols("AUTOTALKS-REG", autotalks=autotalks, atlkMgmt=atlkMgmt)

