# PySNMP SMI module. Autogenerated from smidump -f python AUTOTALKS-TC
# by libsmi2pysnmp-0.1.3 at Tue Aug  4 15:19:14 2015,
# Python version sys.version_info(major=2, minor=7, micro=6, releaselevel='final', serial=0)

# Imports

( Integer, ObjectIdentifier, OctetString, ) = mibBuilder.importSymbols("ASN1", "Integer", "ObjectIdentifier", "OctetString")
( NamedValues, ) = mibBuilder.importSymbols("ASN1-ENUMERATION", "NamedValues")
( ConstraintsIntersection, ConstraintsUnion, SingleValueConstraint, ValueRangeConstraint, ValueSizeConstraint, ) = mibBuilder.importSymbols("ASN1-REFINEMENT", "ConstraintsIntersection", "ConstraintsUnion", "SingleValueConstraint", "ValueRangeConstraint", "ValueSizeConstraint")
( autotalks, ) = mibBuilder.importSymbols("AUTOTALKS-REG", "autotalks")
( Bits, Integer32, ModuleIdentity, MibIdentifier, TimeTicks, ) = mibBuilder.importSymbols("SNMPv2-SMI", "Bits", "Integer32", "ModuleIdentity", "MibIdentifier", "TimeTicks")
( TextualConvention, ) = mibBuilder.importSymbols("SNMPv2-TC", "TextualConvention")

# Types

class ConfigSaveStatus(Integer):
    subtypeSpec = Integer.subtypeSpec+SingleValueConstraint(1,3,0,2,)
    namedValues = NamedValues(("upToDate", 0), ("notUpToDate", 1), ("save", 2), ("saveInProgress", 3), )
    
class LinkProtocolId(Integer32):
    subtypeSpec = Integer32.subtypeSpec+ValueRangeConstraint(0,1099511627775)
    

# Objects

atlkTc = ModuleIdentity((1, 3, 6, 1, 4, 1, 38405, 2)).setRevisions(("2015-07-06 00:00","2014-06-18 00:00","2014-06-18 00:00",))
if mibBuilder.loadTexts: atlkTc.setOrganization("Autotalks")
if mibBuilder.loadTexts: atlkTc.setContactInfo("Grand Netter Building\nPOB 3846, Kfar-Netter 40593, Israel\nPhone: (+972)-9-886-5300\nFax:   (+972)-9-886-5301\ninfo@auto-talks.com")
if mibBuilder.loadTexts: atlkTc.setDescription("Autotalks textual convention module.")

# Augmentions

# Exports

# Module identity
mibBuilder.exportSymbols("AUTOTALKS-TC", PYSNMP_MODULE_ID=atlkTc)

# Types
mibBuilder.exportSymbols("AUTOTALKS-TC", ConfigSaveStatus=ConfigSaveStatus, LinkProtocolId=LinkProtocolId)

# Objects
mibBuilder.exportSymbols("AUTOTALKS-TC", atlkTc=atlkTc)

